add retry for measures download

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,7 +101,17 @@ jobs:
         if: steps.load-cached-casa-measures.outputs.cache-hit != 'true'
         run: |
           mkdir -p ~/measures
-          curl --disable-epsv ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar | tar xvzf - -C ~/measures
+          set -e
+          for i in {1..3}; do
+            if curl --disable-epsv ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar --output WSRT_Measures.ztar; then
+              break
+            elif [ $i -eq 3 ]; then
+              echo "Download failed after 3 attempts."; exit 1
+            else
+              echo "Retrying download..."; sleep 5
+            fi
+          done
+          tar xvzf WSRT_Measures.ztar -C ~/measures
           echo "measures.directory: ~/measures" > ~/.casarc
 
       - name: Install pfb-imaging
